### PR TITLE
Fix OSX bug, TIOCGWINZS from terminal.d

### LINKED ISSUE #19: Error: undefined identifier (TIOCGWINSZ & SIGWINCH)
```sh
Building consoled ~master configuration "library", build type debug.
Running dmd...
dmd -lib -of.dub/build/library-debug-posix.osx-x86_64-dmd_2066-07DFD2109FA006DAE4A88167876EDB72/libconsoled.a -debug -g -w -version=Have_consoled -Isource/ source/consoled.d source/terminal.d
source/consoled.d(759): Error: undefined identifier TIOCGWINSZ
source/terminal.d(1259): Error: undefined identifier SIGWINCH
source/terminal.d(1367): Error: undefined identifier SIGWINCH
FAIL .dub/build/library-debug-posix.osx-x86_64-dmd_2066-07DFD2109FA006DAE4A88167876EDB72/ consoled staticLibrary
Error executing command run:
dmd failed with exit code 1.
```

Not sure why i'm getting this exactly.. from my google searching it seems like these identifiers should resolve to values but they seem to be failing my build. 

```sh
Darwin local.localhost 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64
```

### PR DESCRIPTION
**Pull request by vladdeSV**
Should fix #19

### CODE REVIEW

File: source/consoled.d [hunk 1]
```diff
@@ -753,24 +753,24 @@ else version(Posix)
...
-     * 
+     *
      * Returns:
      *  Tuple containing console rows and cols.
      */
     ConsolePoint size() @property
     {
         winsize w;
-        ioctl(STDOUT_FILENO, TIOCGWINSZ, &w);
+        terminal.ioctl(STDOUT_FILENO, terminal.TIOCGWINSZ, &w);
```
Comment (vladdeSV) [inline source/consoled.d]: Important part here

**Comment by vladdeSV** [comment]
Recommending to create a v1.0.2 after this is merged.

**Comment by grogancolin** [comment]
Can we get this merged please? This bug is ultra annoying on OSX...
